version: '3'

services:
  web:
    container_name: test_web
    build: ./docker/web
    volumes:
      - ./src:/var/www/html
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
      - db
  app:
    container_name: test_app
    build: ./docker/app
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
  db:
    container_name: test_db
    build: ./docker/db
    ports:
      - "33306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: nJVxSSDw8rmuWPuV
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass